# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.runs/synth_1/fpga.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku035-fbva676-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.cache/wt [current_project]
set_property parent.project_path /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/arbiter.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/rtl/axi_ram.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/axis_arb_mux.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/rtl/axis_register.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/rtl/fpga_core.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/pcie_us_axi_dma.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/pcie_us_axi_dma_rd.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/pcie_us_axi_dma_wr.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/pcie_us_axi_master.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/pcie_us_axi_master_rd.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/pcie_us_axi_master_wr.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/pcie_us_axil_master.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/pcie_us_axis_cq_demux.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/pcie_us_cfg.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/pcie_us_msi.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/priority_encoder.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/lib/pcie/rtl/pulse_merge.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/rtl/fpga.v
}
read_ip -quiet /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.srcs/sources_1/ip/pcie3_ultrascale_0/pcie3_ultrascale_0.xci
set_property used_in_implementation false [get_files -all /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/ip_0/synth/pcie3_ultrascale_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/ip_0/synth/pcie3_ultrascale_0_gt.xdc]
set_property used_in_synthesis false [get_files -all /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/source/pcie3_ultrascale_0_ip_impl.xdc]
set_property used_in_implementation false [get_files -all /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/source/pcie3_ultrascale_0_ip_impl.xdc]
set_property used_in_implementation false [get_files -all /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/source/pcie3_ultrascale_0-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/synth/pcie3_ultrascale_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga.xdc
set_property used_in_implementation false [get_files /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fpga -part xcku035-fbva676-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file fpga_utilization_synth.rpt -pb fpga_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
