# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.srcs/sources_1/ip/pcie3_7x_0/pcie3_7x_0.xci
# IP: The module: 'pcie3_7x_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.gen/sources_1/ip/pcie3_7x_0/source/pcie3_7x_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_7x_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.gen/sources_1/ip/pcie3_7x_0/synth/pcie3_7x_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.srcs/sources_1/ip/pcie3_7x_0/pcie3_7x_0.xci
# IP: The module: 'pcie3_7x_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.gen/sources_1/ip/pcie3_7x_0/source/pcie3_7x_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.gen/sources_1/ip/pcie3_7x_0/synth/pcie3_7x_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
