# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.runs/synth_1/fpga.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7vx690tffg1761-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.cache/wt [current_project]
set_property parent.project_path /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files -quiet /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.runs/ten_gig_eth_pcs_pma_1_synth_1/ten_gig_eth_pcs_pma_1.dcp
set_property used_in_implementation false [get_files /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.runs/ten_gig_eth_pcs_pma_1_synth_1/ten_gig_eth_pcs_pma_1.dcp]
add_files -quiet /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.runs/ten_gig_eth_pcs_pma_0_synth_1/ten_gig_eth_pcs_pma_0.dcp
set_property used_in_implementation false [get_files /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.runs/ten_gig_eth_pcs_pma_0_synth_1/ten_gig_eth_pcs_pma_0.dcp]
read_verilog -library xil_defaultlib {
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/arbiter.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/arp.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/arp_cache.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/arp_eth_rx.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/arp_eth_tx.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/rtl/common/axi_ram.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/lib/axis/rtl/axis_adapter.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/lib/axis/rtl/axis_async_fifo.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/lib/axis/rtl/axis_async_fifo_adapter.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/lib/axis/rtl/axis_fifo.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/axis_xgmii_rx_32.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/axis_xgmii_rx_64.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/axis_xgmii_tx_32.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/axis_xgmii_tx_64.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/rtl/debounce_switch.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/dma_if_pcie.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/dma_if_pcie_rd.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/dma_if_pcie_wr.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/dma_psdpram.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/eth_arb_mux.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/eth_axis_rx.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/eth_axis_tx.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/eth_mac_10g.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/eth_mac_10g_fifo.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/rtl/common/example_core.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/rtl/common/example_core_pcie.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/rtl/common/example_core_pcie_us.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/rtl/fpga_core.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/rtl/i2c_master.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/ip_64.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/ip_arb_mux.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/ip_complete_64.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/ip_eth_rx_64.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/ip_eth_tx_64.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/lfsr.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/mac_ctrl_rx.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/mac_ctrl_tx.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/mac_pause_ctrl_rx.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/mac_pause_ctrl_tx.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_axi_master.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_axi_master_rd.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_axi_master_wr.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_axil_master.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_msix.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_tlp_demux.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_tlp_demux_bar.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_tlp_fifo.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_tlp_fifo_raw.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_tlp_mux.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_us_cfg.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_us_if.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_us_if_cc.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_us_if_cq.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_us_if_rc.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_us_if_rq.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pcie_us_msi.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/priority_encoder.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/ptp_clock_cdc.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/pcie/rtl/pulse_merge.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/rtl/si5324_i2c_init.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/rtl/sync_reset.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.gen/sources_1/ip/ten_gig_eth_pcs_pma_0/ten_gig_eth_pcs_pma_0_stub.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.gen/sources_1/ip/ten_gig_eth_pcs_pma_1/ten_gig_eth_pcs_pma_1_stub.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/udp_64.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/udp_checksum_gen_64.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/udp_complete_64.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/udp_ip_rx_64.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/rtl/udp_ip_tx_64.v
  /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/rtl/fpga.v
}
read_ip -quiet /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.srcs/sources_1/ip/pcie3_7x_0/pcie3_7x_0.xci
set_property used_in_implementation false [get_files -all /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.gen/sources_1/ip/pcie3_7x_0/source/pcie3_7x_0-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.gen/sources_1/ip/pcie3_7x_0/synth/pcie3_7x_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga.xdc
set_property used_in_implementation false [get_files /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga.xdc]

read_xdc -unmanaged /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/syn/vivado/eth_mac_fifo.tcl
set_property used_in_implementation false [get_files /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/syn/vivado/eth_mac_fifo.tcl]

read_xdc -unmanaged /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/lib/axis/syn/vivado/axis_async_fifo.tcl
set_property used_in_implementation false [get_files /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/lib/axis/syn/vivado/axis_async_fifo.tcl]

read_xdc -unmanaged /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/lib/axis/syn/vivado/sync_reset.tcl
set_property used_in_implementation false [get_files /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/lib/eth/lib/axis/syn/vivado/sync_reset.tcl]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/fpga/fpga/fpga.srcs/utils_1/imports/synth_1/fpga.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fpga -part xc7vx690tffg1761-3
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file fpga_utilization_synth.rpt -pb fpga_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
