# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.srcs/sources_1/ip/pcie3_ultrascale_0/pcie3_ultrascale_0.xci
# IP: The module: 'pcie3_ultrascale_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/ip_0/pcie3_ultrascale_0_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie3_ultrascale_0_gt || ORIG_REF_NAME==pcie3_ultrascale_0_gt} -quiet] -quiet

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/ip_0/synth/pcie3_ultrascale_0_gt_ooc.xdc

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/ip_0/synth/pcie3_ultrascale_0_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie3_ultrascale_0_gt || ORIG_REF_NAME==pcie3_ultrascale_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/source/pcie3_ultrascale_0_ip_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_ultrascale_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/source/pcie3_ultrascale_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_ultrascale_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/synth/pcie3_ultrascale_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_ultrascale_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.srcs/sources_1/ip/pcie3_ultrascale_0/pcie3_ultrascale_0.xci
# IP: The module: 'pcie3_ultrascale_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/ip_0/pcie3_ultrascale_0_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie3_ultrascale_0_gt || ORIG_REF_NAME==pcie3_ultrascale_0_gt} -quiet] -quiet

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/ip_0/synth/pcie3_ultrascale_0_gt_ooc.xdc

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/ip_0/synth/pcie3_ultrascale_0_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie3_ultrascale_0_gt || ORIG_REF_NAME==pcie3_ultrascale_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/source/pcie3_ultrascale_0_ip_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_ultrascale_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/source/pcie3_ultrascale_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_ultrascale_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/luisfercrtez/Documents/Master/Tesis/NetFPGA-SUME/firmware/verilog-pcie-master/example/ExaNIC_X10/fpga_axi/fpga/fpga.gen/sources_1/ip/pcie3_ultrascale_0/synth/pcie3_ultrascale_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_ultrascale_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
